### ISSUE TITLE
Question: Why oneAtATime is used in SetInitializer function?

### ISSUE THREAD

**Issue by richzw** [tflyons/httpx#1]
I am confused why the channel `oneAtATime` is used in `SetInitializer` function. Could someone give me some clues?

Thanks

**Comment by tflyons** [comment]
Good question, the channel is there to act as a lock and conditional. When a client first makes a request the initializer is called. If it succeeds then the channel is closed so all future calls will skip attempting to initialize. However, if it fails then an error is returned and the next client to make a request will reattempt to initialize. 

We want to block so only one client is initializing at a time, but once the initializer succeeds and the channel is closed the lock no longer applies.

**Comment by richzw** [comment]
@tflyons , Thank you very much for your detailed response. 

I misunderstood this function `SetInitializer` with the case `SetInitializer` was called multiple times, actually, it should belong different client.

**Comment by tflyons** [comment]
Happy to help
